### ISSUE TITLE
Still having trouble creating accounts

### ISSUE THREAD

**Issue by tasneem** [motherjones/datawrapper#14]
AJ reports that he never got the email invite to create his account.

And I've asked for a password reset email, but that hasn't come through either. 

These emails don't appear to be getting caught in Quarantine Summary, as far as I can tell.

**Comment by soycamo** [comment]
Accounts have been regenerated and emails have been sent.

**Comment by soycamo** [comment]
I switched the mail server and remade your account. All mail was marked as delivered.
