### ISSUE TITLE
ec2 link leads to error message

### ISSUE THREAD

**Issue by jaeahlee** [motherjones/datawrapper#15]
opened the link to preview my changes to mojo.js (for datawrapper-theme-mojo) and got this error message (see below). any ideas?

![screen shot 2014-07-29 at 12 15 04 pm](https://cloud.githubusercontent.com/assets/1892121/3740526/67e6efaa-1756-11e4-9111-1c8a7301aa48.png)

**Comment by soycamo** [comment]
You have to reboot MySQL. It does this like, everyday. Type `sudo service mysqld restart` and you should be good.

**Comment by jaeahlee** [comment]
Thanks!
