### ISSUE TITLE
Make homepage customizable

### ISSUE THREAD

**Issue by tasneem** [motherjones/datawrapper#2]

**Comment by tasneem** [comment]
From DW docs:
1. Create a new Twig template (that is basically an HTML file with some special tags) and store it into /templates/custom/, e.g. my-home-template.twig.
2. Edit config.yaml and add the following line. Replace my-home-template with the filename of your new Twig template (without the extension .twig):
   custom_home: my-home-template

**Comment by soycamo** [comment]
What should be on the homepage?

**Comment by soycamo** [comment]
The file is located at /templates/custom/staff_home.twig.
