### ISSUE TITLE
Change default chart width to 100% not 630px

### ISSUE THREAD

**Issue by tasneem** [motherjones/datawrapper#20]

**Comment by jaeahlee** [comment]
Cameron, can you see about making the default width in the chart iframe embed codes to be width="100%", instead of the current width="630px"?

**Comment by jaeahlee** [comment]
this issue is the same as https://github.com/motherjones/datawrapper/issues/28

**Comment by cadamez** [comment]
I don't think Datawrapper works this way.

**Comment by jaeahlee** [comment]
Cam: I see. How so? My guess was that whatever we did to set the width at 630px wide, we should change to 100%? Unless the 630px wide is a default Datawrapper thing we never customized in the first place?

**Comment by cadamez** [comment]
This is a known problem for Datawrapper itself and the way the iframes are inserted.

**Comment by maxhartshorn** [comment]
Hi cadamez. Could you explain a little more about why datawrapper wont fix this? Datawrapper's charts are nicely responsive but reporters at our organization have to remember to change 630px to 100% to take advantage of this capability, which they often don't do. It would be great to an option to set 100% as the default width, or at least an option to set it to 100% at all in the interface.
