### ISSUE TITLE
Possible to store chart output on s3, not the ec2 server?

### ISSUE THREAD

**Issue by tasneem** [motherjones/datawrapper#6]

**Comment by tasneem** [comment]
Since the chart output isn't dynamic, can we use the existing interactives directory on the mojo s3 to store the chart data? 

/mjassets/interactives/

**Comment by soycamo** [comment]
I set up the test instance with test s3 credentials, but I think I might be missing a plugin that isn't included upstream (in the original datawrapper repo)

**Comment by soycamo** [comment]
Recent fork https://github.com/motherjones/plugin-publish-s3 should resolve this issue.
