### ISSUE TITLE
Chart iframe JS cannot be found

### ISSUE THREAD

**Issue by soycamo** [motherjones/datawrapper#7]
the JavaScript paths for an individual chart appear to be malformed.

**Comment by tasneem** [comment]
Was able to generate iframe embed code, but chart data is still missing: 

http://www.motherjones.com/mixed-media/2014/06/testing-post
![screen shot 2014-06-04 at 1 25 33 pm](https://cloud.githubusercontent.com/assets/164117/3177984/a89f5f8a-ec15-11e3-9f2b-20fd50fc184a.png)

**Comment by soycamo** [comment]
Charts should now be working as of cf3091e5f68c733e2836544145d081ebe89e0ed9 :sweat_smile: 
I'll resend the URL if you don't have it.
